name: 'harvest_dbt'
version: '1.0.0'
profile: 'harvest_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  harvest_dbt:
    staging:
      +materialized: view
    dwh:
      +materialized: table